
dist: focal
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    curl -f -T lesson_project-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -urfootq:$BINTRAY_API_KEY "https://api.bintray.com/content/rfootq/PracticalWork/lesson1/$TRAVIS_BUILD_NUMBER/lesson_project-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=focal;deb_component=main;deb_architecture=amd64;publish=1"